M48
; DRILL file {KiCad 7.0.2} date Tue Oct 24 21:55:32 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-24T21:55:32-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X121.44Y-75.52
X139.93Y-75.52
T2
X113.27Y-67.9
X113.27Y-70.44
X113.27Y-72.98
X113.27Y-75.52
T0
M30
